checks:
  title-validator:
    matches:
      - ^bug-.*
      - ^enhancement-.*
    failure-message: |2
      Pull Request Validation Failed. The pull request title should follow the below case-sensitive patterns
      * `bug-An optional small summary title`
      * `enhancement-An optional small summary title`
      * `Revert "bug-An optional small summary title"`
      * `Revert "enhancement-An optional small summary title"`